import type { Metadata } from "next";
import "./globals.css";
import { health } from "./_data/health";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  health("RootLayout")
  return (
    <html
      lang="jp"
      className="h-full antialiased"
      suppressHydrationWarning // Chrome拡張機能のカスタム属性がCC側でアタッチされることでエラーになることがあるので無視する（html属性配下には影響がない。ただし基本的にhtmlタグ以外に付与することは禁止する）
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
